### ISSUE TITLE
MorphologistSimple fails to run in soma-workflow in a user image

### ISSUE THREAD

**Issue by ylep** [brainvisa/morphologist-gpl#6]
**Describe the bug**

```
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/casa/install/python/capsul/process/process.py", line 744, in run_from_commandline

    result = ce.study_config.run(process, configuration_dict=configuration)

  File "/casa/install/python/capsul/study_config/study_config.py", line 424, in run

    result, log_file = run_process(

  File "/casa/install/python/capsul/study_config/run.py", line 165, in run_process

    returncode = process_instance._run_process()

  File "/casa/install/python/morphologist/capsul/axon/morphologistprocess.py", line 207, in _run_process

    context.runProcess('morphologistProcess', **kwargs)

  File "/casa/install/python/brainvisa/processes.py", line 3112, in runProcess

    self._setArguments(_process, *args, **kwargs)

  File "/casa/install/python/brainvisa/processes.py", line 3073, in _setArguments

    _process.checkArguments()

  File "/casa/install/python/brainvisa/processes.py", line 957, in checkArguments

    o.checkValue(p, getattr(self, p, None))

  File "/casa/install/python/brainvisa/data/readdiskitem.py", line 237, in checkValue

    raise RuntimeError(

RuntimeError: the parameter <em>sulci_file</em> is not readable or does not exist : /casa/host/build/share/brainvisa-share-5.1/nomenclature/translation/sulci_default_list.json
```

**To Reproduce**
1. In Axon, generate a workflow file using **Morphologist CAPSUL iteration**, using **Morphologist simple** as **capsul_process_type**;
2. Try to run this workflow e.g. on the alambic cluster
3. See the exception above: the model files are looked up in `/casa/host/build` instead of `/casa/install`.

**Environment:**
 - Engine: Singularity
 - Version of BrainVISA: 5.1 branch

**Additional context**
I am using a user image based on a quite recent `5.1` branch, which does include the fix for https://github.com/brainvisa/morphologist-gpl/issues/5

**Comment by denisri** [comment]
(and in the latter case, not only morphologist-simple is affected: every process using shared data will also suffer from this issue)

**Comment by denisri** [comment]
The FOM issue is fixed.
The path translation automation issue is not.
